### ISSUE TITLE
Enforce package.json dependency

### ISSUE THREAD

**Issue by azz** [azz/eslint-plugin-monorepo#4]
Sometimes in a monorepo one will forget to add a dependency to a package's `package.json` and it will continue to work because the dependency was hoisted from another package, or it is installed in the root. This means the package cannot be individually installed so should be prevented.

**Comment by benmosher** [comment]
Ahh, neat, so like a monorepo-internal version of `import/no-extraneous-dependencies`?

**Comment by azz** [comment]
Yeah, I thought at the time that `import/no-extraneous-dependencies` wasn't sufficient, but I've been using it for a while and it seems to suffice.
