### ISSUE TITLE
Upgrade get-monorepo-packages

### ISSUE THREAD

**Issue by swarchen** [azz/eslint-plugin-monorepo#6]
`get-monorepo-packages` now support yarn 1.4.2+ workspaces format

[feat: support yarn 1.4.2+ workspaces format](https://github.com/azz/get-monorepo-packages/commit/087e878a95224e1e2907d497bab8e53f366c08a4)

```js
"workspaces": {
  "packages": ["packages/*"],
}
```

- [nohoist in Workspaces | Yarn Blog](https://yarnpkg.com/blog/2018/02/15/nohoist/)

**Comment by AlonMiz** [comment]
get-monorepo-packages has been update to 1.1.0 and support this format
Approve this pls :)
https://github.com/azz/eslint-plugin-monorepo/pull/7
